%custo(Tratamento, Custo)
custo(paracetamol, 5).
custo(brufen, 4).
custo(aspirina, 2).
custo(anti_histaminico, 8).
custo(descanso, 100).
custo(fisioterapia, 150).
custo(cine_terapia, 200).
custo(desporto, 0).
custo(cirurgia, 1200).
custo(inalacoes, 50).
custo(insulina, 34).
custo(antibiotico, 25).
custo(dieta, 0).
custo(ginastica, 90).
custo(internamento, 250).
custo(dialise, 100).
custo(calmante, 80).
custo(injecoes, 75).
custo(inalo_terapia, 90).
custo(soro, 15).
custo(oculos, 500).
custo(lentes_contacto, 300).
custo(operacao, 800).

doenca(gripe, paracetamol).
doenca(gripe, brufen).
doenca(gripe, descanso).
doenca(gripe, aspirina).
doenca(alergia, anti_histaminico).
doenca(alergia, inalacoes).
doenca(diabete, insulina).
doenca(diabete, dieta).
doenca(infeccao, antibiotico).
doenca(infeccao, descanso).
doenca(infeccao, internamento).
doenca(doenca_renal, dialise).
doenca(doenca_renal, soro).
doenca(ansiedade, calmante).
doenca(ansiedade, desporto).
doenca(ansiedade, ginastica).
doenca(lesao, fisioterapia).
doenca(lesao, descanso).
doenca(lesao, cirurgia).
doenca(problema_ocular, oculos).
doenca(problema_ocular, lentes_contacto).
doenca(problema_ocular, cirurgia).
doenca(asma, inalacoes).
doenca(asma, inalo_terapia).


% Define the duracao/3 predicate
duracao(paracetamol, 2).
duracao(brufen, 3).
duracao(aspirina, 4).
duracao(anti_histaminico, 5).
duracao(descanso, 2).
duracao(inalacoes, 10).
duracao(insulina, 30).
duracao(dieta, 30).
duracao(antibiotico, 8).
duracao(descanso, 2).
duracao(internamento, 3).
duracao(dialise, 10).
duracao(soro, 8).
duracao(desporto, 12).
duracao(calmante, 90).
duracao(ginastica, 15).
duracao(fisioterapia, 6).
duracao(descanso, 2).
duracao(cirurgia, 3).
duracao(oculos, 1000).
duracao(lentes_contacto, 200).
duracao(inalo_terapia, 6).
duracao(inalacoes, 10).


%arco(Origem, Destino)
arco(origem, paracetamol).
arco(origem, brufen).
arco(origem, aspirina).
arco(origem, anti_histaminico).
arco(origem, descanso).
arco(paracetamol, descanso).
arco(brufen, descanso).
arco(paracetamol, fisioterapia).
arco(brufen, fisioterapia).
arco(paracetamol, cine_terapia).
arco(descanso, cine_terapia).
arco(cine_terapia, fim).
arco(brufen, desporto).
arco(fisioterapia, cirurgia).
arco(fisioterapia, fim).
arco(aspirina, inalacoes).
arco(aspirina, insulina).
arco(paracetamol, antibiotico).
arco(aspirina, antibiotico).
arco(anti_histaminico, antibiotico).
arco(antibiotico, fim).
arco(aspirina, dieta).
arco(desporto, dieta).
arco(dieta, fim).
arco(brufen, ginastica).
arco(fisioterapia, ginastica).
arco(anti_histaminico, internamento).
arco(cirurgia, internamento).
arco(antibiotico, internamento).
arco(internamento, fim).
arco(insulina, dialise).
arco(dialise, fim).
arco(fisioterapia, calmante).
arco(cine_terapia, calmante).
arco(desporto, calmante).
arco(fisioterapia, injecoes).
arco(insulina, injecoes).
arco(injecoes, inalo_terapia).
arco(inalo_terapia, fim).
arco(aspirina, soro).
arco(cirurgia, soro).
arco(inalacoes, soro).
arco(internamento, soro).
arco(paracetamol, oculos).
arco(brufen, oculos).
arco(aspirina, oculos).
arco(descanso, oculos).
arco(oculos, fim).
arco(paracetamol, lentes_contacto).
arco(brufen, lentes_contacto).
arco(aspirina, lentes_contacto).
arco(descanso, lentes_contacto).
arco(lentes_contacto, fim).
arco(descanso, ambulatorio).
arco(ginastica, ambulatorio).
arco(fisioterapia, ambulatorio).
arco(calmante, ambulatorio).
arco(injecoes, ambulatorio).
arco(soro, ambulatorio).
arco(ambulatorio, fim).
